// data.js — Portfolio content data for Nicol Cuello Alvarez (Multilingual Support)

export const PROFILE = {
  name: "Nicol Cuello Alvarez",
  role: "Tecnóloga en Desarrollo de Software & QA Engineer",
  tagline: "Construyendo software de calidad con código sólido y pruebas automatizadas",
  bio: `Tecnóloga en Desarrollo de Software con sólida base en el desarrollo backend, automatización de casos de prueba y manejo de bases de datos. Me caracterizo por mi capacidad analítica, atención al detalle y enfoque en la resolución de problemas. Soy una profesional proactiva, orientada al aprendizaje continuo y al trabajo en equipo, con interés en aportar valor y seguir desarrollándome en entornos tecnológicos.`,
  email: "nicolcuelloa@gmail.com",
  linkedin: "linkedin.com/in/ncl27/",
  github: "github.com/NCL27",
  location: "República Dominicana",
  stats: [
    { number: "3+", label: "Años de Exp." },
    { number: "3", label: "Roles de QA" },
  ],
};

export const SKILLS = {
  development: [
    { name: "JavaScript", pct: 90, tags: ["tag-cyan"] },
    { name: "TypeScript", pct: 85, tags: ["tag-cyan"] },
    { name: "Python", pct: 82, tags: ["tag-cyan"] },
    { name: "C#", pct: 80, tags: ["tag-purple"] },
    { name: "C++", pct: 75, tags: ["tag-purple"] },
    { name: "SQL", pct: 88, tags: ["tag-gold"] },
  ],
  qa: [
    { name: "Cypress & JavaScript", pct: 90, tags: ["tag-green"] },
    { name: "Selenium", pct: 85, tags: ["tag-green"] },
    { name: "Postman (API Testing)", pct: 88, tags: ["tag-green"] },
    { name: "Android Studio (Mobile Testing)", pct: 82, tags: ["tag-red"] },
    { name: "Jira & Azure DevOps", pct: 85, tags: ["tag-purple"] },
  ],
  tools: ["Selenium", "Cypress", "Postman", "MongoDB", "Oracle SQL Developer", "Android Studio", "Transact", "Git & GitHub", "Jira & Azure DevOps"],
};

export const EXPERIENCE = [
  {
    role: "Quality Assurance Engineer",
    company: "Babel Group",
    period: "Febrero 2026 – Presente",
    type: "Full-time",
    desc: "QA Engineer en el proyecto PYME del Banco BHD. Responsable del desarrollo de escenarios, ejecución de casos de pruebas, y elaboración y gestión del plan de pruebas en Jira y Azure DevOps, organizando escenarios y casos.",
    tags: ["Jira", "Azure DevOps", "Banco BHD", "Test Planning", "tag-green"],
  },
  {
    role: "Quality Assurance Specialist I",
    company: "Babel Group",
    period: "Agosto 2025 – Diciembre 2025",
    type: "Full-time",
    desc: "QA en el proyecto Core del Banco Popular Dominicano. Gestión en Transact (creación de usuarios, desembolso de préstamos) y soporte en UAT a usuarios móviles detectando errores con Android Studio. Desarrollo de pruebas automatizadas en Siebel con Cypress y JavaScript, y automatización de casos de prueba usando Postman para validación de APIs.",
    tags: ["Cypress", "JavaScript", "Postman", "Android Studio", "Transact", "tag-green"],
  },
  {
    role: "Intern Quality Assurance Specialist",
    company: "Babel Group",
    period: "Marzo 2025 – Agosto 2025",
    type: "Internship",
    desc: "Ejecución de pruebas funcionales para asegurar el correcto funcionamiento y la calidad del software. Automatización de casos de prueba mediante la creación y mantenimiento de scripts de automatización.",
    tags: ["Manual Testing", "Test Automation", "QA Processes", "tag-cyan"],
  },
  {
    role: "Profesora de clases particulares",
    company: "Robothink",
    period: "Abril 2023 – Agosto 2025",
    type: "Part-time",
    desc: "Impartí clases de robótica y programación a niños de entre 6 y 13 años, fomentando el pensamiento crítico, la creatividad y el trabajo en equipo mediante proyectos y el uso de tecnologías educativas.",
    tags: ["Python", "C++", "Robotics", "Teaching", "tag-purple"],
  },
];

export const PROJECTS = [
  {
    name: "Pokedex",
    status: "completed",
    desc: "Aplicación Pokedex implementada en .NET aplicando arquitectura limpia (Clean Architecture), con separación de capas para Dominio, Aplicación, Base de Datos y Presentación.",
    tech: ["C#", ".NET", "Clean Architecture", "SQL Server"],
    github: "https://github.com/NCL27/Pokedex",
  },
];

export const EDUCATION = [
  {
    degree: "Tecnóloga en Desarrollo de Software",
    school: "Instituto Tecnológico de las Américas (ITLA)",
    period: "Octubre 2025",
    desc: "Formación especializada de educación superior en ingeniería de software, backend, bases de datos y desarrollo web.",
  },
  {
    degree: "Desarrollo y Administración de Aplicaciones Informáticas",
    school: "Instituto Técnico Salesiano (ITESA)",
    period: "Octubre 2021",
    desc: "Título técnico enfocado en fundamentos de programación, bases de datos y administración de sistemas.",
  },
];

export const CERTIFICATIONS = [
  { name: "Scrum Fundamentals Certified", issuer: "Scrum Study", year: "2025", icon: "🏅" },
  { name: "ISTQB® Certified Tester, Foundation Level (v4.0)", issuer: "ISTQB", year: "2025", icon: "🏅" },
  { name: "Postman API Fundamentals Student Expert", issuer: "Postman", year: "2025", icon: "🏅" },
];

export const PLANETS = [
  {
    id: "about",
    name: "Inicio",
    designation: "SOL-01",
    emoji: "👨‍🚀",
    size: 2.2,
    orbitRadius: 0,
    isSun: true,
    color: "#ffd700",
    glowColor: "#ff8800",
    speed: 0,
    eccentricity: 0,
    inclination: 0,
    section: "about",
    hint: "Sobre mí",
  },
  {
    id: "skills",
    name: "Habilidades",
    designation: "MRY-02",
    emoji: "⚡",
    size: 0.7,
    orbitRadius: 8,
    color: "#b5a3ff",
    glowColor: "#6c63ff",
    speed: 0.8,
    eccentricity: 0.21,
    inclination: 7,
    tilt: 5,
    section: "skills",
    hint: "Tech Skills",
  },
  {
    id: "experience",
    name: "Experiencia",
    designation: "VNS-03",
    emoji: "💼",
    size: 1.1,
    orbitRadius: 13,
    color: "#7ecfff",
    glowColor: "#00d4ff",
    speed: 0.5,
    eccentricity: 0.12,
    inclination: 3.4,
    tilt: 15,
    section: "experience",
    hint: "Work Experience",
  },
  {
    id: "projects",
    name: "Proyectos",
    designation: "MRS-04",
    emoji: "🚀",
    size: 0.95,
    orbitRadius: 19,
    color: "#ff9a56",
    glowColor: "#ff6b35",
    speed: 0.35,
    eccentricity: 0.09,
    inclination: 1.9,
    rings: true,
    tilt: 20,
    section: "projects",
    hint: "Mis Proyectos",
  },
  {
    id: "education",
    name: "Educación",
    designation: "JPT-05",
    emoji: "🎓",
    size: 1.3,
    orbitRadius: 26,
    color: "#ffd166",
    glowColor: "#f5a623",
    speed: 0.22,
    eccentricity: 0.05,
    inclination: 1.3,
    tilt: 3,
    section: "education",
    hint: "Educación & Certs",
  },
  {
    id: "contact",
    name: "Contacto",
    designation: "NPT-06",
    emoji: "📡",
    size: 0.65,
    orbitRadius: 32,
    color: "#70efde",
    glowColor: "#00ff88",
    speed: 0.15,
    eccentricity: 0.17,
    inclination: 5.5,
    tilt: 10,
    section: "contact",
    hint: "¡Hablemos!",
  },
];

// ---- MULTILINGUAL TRANSLATIONS SYSTEM ----
export const TRANSLATIONS = {
  es: {
    profile: PROFILE,
    skills: SKILLS,
    experience: EXPERIENCE,
    projects: PROJECTS,
    education: EDUCATION,
    certifications: CERTIFICATIONS,
    planets: PLANETS,
    ui: {
      sectorLabel: "SECTOR",
      sectorValue: "SOL-7 · ALCUNI.DEV",
      systemActive: "SISTEMA ACTIVO",
      controlsHint: "⟁ ARRASTRA PARA ORBITAR · ⬡ SCROLL PARA ZOOM · ◎ CLICK EN PLANETAS",
      mobileHint: "👆 Arrastra · 🤏 Pellizca para zoom · Toca un planeta",
      telemetryStatus: "ENLACE OK",
      telemetryDist: "DISTANCIA:",
      telemetryVel: "VELOCIDAD:",
      resetBtn: "RESET",
      loaderText: "Iniciando sistema solar",
      actionBtnBio: "VER BIOGRAFÍA DEL SISTEMA >_",
      actionBtnDetails: "VER DETALLES: {name} >_",
      telemetryDescs: {
        about: "Módulo central del sistema. Datos personales, rol y biografía general del desarrollador.",
        skills: "Matriz de competencias técnicas. Suite de pruebas unitarias sobre stacks de Desarrollo y QA.",
        experience: "Historial de despliegues profesionales. Registro de experiencias previas en desarrollo y automatización.",
        projects: "Registro de servicios y repositorios. Estado de integridad y links a proyectos destacados.",
        education: "Certificados académicos y credenciales verificadas. Módulos recreativos adicionales (Space Pacman).",
        contact: "Canal de comunicaciones activo. Enlaces directos para envío de correos y redes profesionales."
      },
      panels: {
        cv: {
          title: "CV",
          subtitle: "ARMAGEDON",
          export: "⬇ EXPORTAR",
          pdfPath: "/Nicol Cuello Alvarez, Desarrolladora en software.pdf",
          pdfDownloadName: "Nicol_Cuello_Alvarez_CV_ES.pdf"
        },
        about: {
          bootCheck: "SYSTEM BOOT CHECK: OK",
          runningStatus: "● CORRIENDO",
          hello: "Hola, soy",
          rolePrefix: "ROLE:",
          orbitalControl: "🌌 CONTROL DE ORBITAS",
          telemetryHelp: "$ telemetry --help",
          telemetryHint: "Cada planeta representa una sección del CV.",
          dragHint: "🖱️ MOUSE ARRASTRAR:",
          dragDesc: "Rotar órbita.",
          scrollHint: "🖲️ MOUSE SCROLL:",
          scrollDesc: "Control de Zoom.",
          clickHint: "◎ CLICK EN PLANETA:",
          clickDesc: "Cargar módulo.",
          keplerianText: "* Trayectorias Keplerianas elípticas cargadas."
        },
        skills: {
          testResults: "RESULTADOS PRUEBAS: 12 COMPLETADAS, 0 FALLIDAS",
          systemOnline: "● SISTEMA ONLINE",
          devStack: "💻 TEST SUITE: DEVELOPMENT_STACK",
          qaStack: "🧪 TEST SUITE: QA_AUTOMATION_STACK",
          toolsHeader: "🔧 HERRAMIENTAS & PIPELINE CI_CD"
        },
        experience: {
          pipelineHistory: "HISTORIAL PIPELINE: ESTABLE",
          status: "ESTADO: ACTIVO",
          deploySuccess: "DESPLIEGUE EXITOSO"
        },
        projects: {
          status: "ESTADO INTEGRACIÓN PROYECTOS: ACTIVO",
          repos: "REPOSITORIOS: {count}",
          telemetrySignal: "SEÑAL DE TELEMETRÍA",
          stable: "ESTABLE",
          viewSource: ">_ VER CÓDIGO FUENTE"
        },
        education: {
          registrySystem: "SISTEMA REGISTRO CERTIFICACIONES",
          verified: "VERIFICADO: OK",
          academicDegrees: "🎓 TÍTULOS ACADÉMICOS",
          certsAndBadges: "🏅 CERTIFICACIONES & INSIGNIAS",
          verifiedCheck: "✓ VERIFICADO",
          recSystems: "👾 SISTEMAS RECREATIVOS",
          simulationCmd: "$ run simulation --pacman",
          simulationDesc: "¿Quieres probar la simulación recreativa del sistema? Controla al Sol y devora los planetas en miniatura.",
          simulationBtn: "🎮 EJECUTAR SIMULACIÓN PACMAN"
        },
        contact: {
          initialized: "CANAL COMUNICACIÓN INICIALIZADO",
          txActive: "📡 TX_ACTIVA",
          pingCmd: "> ping -c 1 cliente-hr",
          pingDesc: "Listo para recibir transmisiones de ofertas laborales, proyectos freelance o colaboraciones en software libre. Establece el canal de conexión abajo:"
        }
      }
    }
  },
  en: {
    profile: {
      ...PROFILE,
      role: "Software Development Technologist & QA Engineer",
      tagline: "Building quality software with solid code and automated tests",
      bio: "Software Development Technologist with a solid foundation in backend development, test case automation, and database management. I am characterized by my analytical capability, attention to detail, and focus on problem solving. I am a proactive professional, oriented towards continuous learning and teamwork, with an interest in adding value and continuing to develop in tech environments.",
      stats: [
        { number: "3+", label: "Years of Exp." },
        { number: "3", label: "QA Roles" },
      ]
    },
    skills: SKILLS,
    experience: [
      {
        role: "Quality Assurance Engineer",
        company: "Babel Group",
        period: "February 2026 – Present",
        type: "Full-time",
        desc: "QA Engineer in the BHD Bank SME project. Responsible for scenario development, execution of test cases, and preparation and management of the test plan in Jira and Azure DevOps, organizing scenarios and cases.",
        tags: ["Jira", "Azure DevOps", "Banco BHD", "Test Planning", "tag-green"],
      },
      {
        role: "Quality Assurance Specialist I",
        company: "Babel Group",
        period: "August 2025 – December 2025",
        type: "Full-time",
        desc: "QA in the Core project of Banco Popular Dominicano. Management in Transact (user creation, loan disbursement) and support in UAT to mobile users detecting errors with Android Studio. Development of automated tests in Siebel with Cypress and JavaScript, and test case automation using Postman for API validation.",
        tags: ["Cypress", "JavaScript", "Postman", "Android Studio", "Transact", "tag-green"],
      },
      {
        role: "Intern Quality Assurance Specialist",
        company: "Babel Group",
        period: "March 2025 – August 2025",
        type: "Internship",
        desc: "Execution of functional tests to ensure proper functioning and quality of the software. Automation of test cases through the creation and maintenance of automation scripts.",
        tags: ["Manual Testing", "Test Automation", "QA Processes", "tag-cyan"],
      },
      {
        role: "Private Tutor",
        company: "Robothink",
        period: "April 2023 – August 2025",
        type: "Part-time",
        desc: "Taught robotics and programming classes to children aged 6 to 13, fostering critical thinking, creativity, and teamwork through projects and the use of educational technologies.",
        tags: ["Python", "C++", "Robotics", "Teaching", "tag-purple"],
      },
    ],
    projects: [
      {
        name: "Pokedex",
        status: "completed",
        desc: "Pokedex application implemented in .NET applying clean architecture (Clean Architecture), with layer separation for Domain, Application, Database, and Presentation.",
        tech: ["C#", ".NET", "Clean Architecture", "SQL Server"],
        github: "https://github.com/NCL27/Pokedex",
      }
    ],
    education: [
      {
        degree: "Software Development Technologist",
        school: "Instituto Tecnológico de las Américas (ITLA)",
        period: "October 2025",
        desc: "Specialized higher education in software engineering, backend, databases, and web development.",
      },
      {
        degree: "Development and Administration of Computer Applications",
        school: "Instituto Técnico Salesiano (ITESA)",
        period: "October 2021",
        desc: "Technical degree focused on programming fundamentals, databases, and systems administration.",
      },
    ],
    certifications: CERTIFICATIONS,
    planets: [
      {
        id: "about",
        name: "Home",
        designation: "SOL-01",
        emoji: "👨‍🚀",
        size: 2.2,
        orbitRadius: 0,
        isSun: true,
        color: "#ffd700",
        glowColor: "#ff8800",
        speed: 0,
        eccentricity: 0,
        inclination: 0,
        section: "about",
        hint: "About me",
      },
      {
        id: "skills",
        name: "Skills",
        designation: "MRY-02",
        emoji: "⚡",
        size: 0.7,
        orbitRadius: 8,
        color: "#b5a3ff",
        glowColor: "#6c63ff",
        speed: 0.8,
        eccentricity: 0.21,
        inclination: 7,
        tilt: 5,
        section: "skills",
        hint: "Tech Skills",
      },
      {
        id: "experience",
        name: "Experience",
        designation: "VNS-03",
        emoji: "💼",
        size: 1.1,
        orbitRadius: 13,
        color: "#7ecfff",
        glowColor: "#00d4ff",
        speed: 0.5,
        eccentricity: 0.12,
        inclination: 3.4,
        tilt: 15,
        section: "experience",
        hint: "Work Experience",
      },
      {
        id: "projects",
        name: "Projects",
        designation: "MRS-04",
        emoji: "🚀",
        size: 0.95,
        orbitRadius: 19,
        color: "#ff9a56",
        glowColor: "#ff6b35",
        speed: 0.35,
        eccentricity: 0.09,
        inclination: 1.9,
        rings: true,
        tilt: 20,
        section: "projects",
        hint: "My Projects",
      },
      {
        id: "education",
        name: "Education",
        designation: "JPT-05",
        emoji: "🎓",
        size: 1.3,
        orbitRadius: 26,
        color: "#ffd166",
        glowColor: "#f5a623",
        speed: 0.22,
        eccentricity: 0.05,
        inclination: 1.3,
        tilt: 3,
        section: "education",
        hint: "Education & Certs",
      },
      {
        id: "contact",
        name: "Contact",
        designation: "NPT-06",
        emoji: "📡",
        size: 0.65,
        orbitRadius: 32,
        color: "#70efde",
        glowColor: "#00ff88",
        speed: 0.15,
        eccentricity: 0.17,
        inclination: 5.5,
        tilt: 10,
        section: "contact",
        hint: "Let's talk!",
      },
    ],
    ui: {
      sectorLabel: "SECTOR",
      sectorValue: "SOL-7 · ALCUNI.DEV",
      systemActive: "SYSTEM ACTIVE",
      controlsHint: "⟁ DRAG TO ORBIT · ⬡ SCROLL TO ZOOM · ◎ CLICK PLANETS",
      mobileHint: "👆 Drag · 🤏 Pinch to zoom · Tap a planet",
      telemetryStatus: "LINK OK",
      telemetryDist: "DISTANCE:",
      telemetryVel: "SPEED:",
      resetBtn: "RESET",
      loaderText: "Initializing solar system",
      actionBtnBio: "VIEW SYSTEM BIOGRAPHY >_",
      actionBtnDetails: "VIEW DETAILS: {name} >_",
      telemetryDescs: {
        about: "System central module. Personal data, role, and general developer biography.",
        skills: "Technical skills matrix. Unit test suite running on Development and QA stacks.",
        experience: "Professional deployment logs. Registry of previous experience in development and automation.",
        projects: "Services and repositories registry. Integrity status and links to featured projects.",
        education: "Academic degrees and verified credentials. Additional recreational modules (Space Pacman).",
        contact: "Active communication channel. Direct links for emails and professional networks."
      },
      panels: {
        cv: {
          title: "CV",
          subtitle: "ARMAGEDDON",
          export: "⬇ EXPORT",
          pdfPath: "/Nicol Cuello Alvarez, Software Development .pdf",
          pdfDownloadName: "Nicol_Cuello_Alvarez_CV_EN.pdf"
        },
        about: {
          bootCheck: "SYSTEM BOOT CHECK: OK",
          runningStatus: "● RUNNING",
          hello: "Hi, I am",
          rolePrefix: "ROLE:",
          orbitalControl: "🌌 ORBITAL CONTROL",
          telemetryHelp: "$ telemetry --help",
          telemetryHint: "Each planet represents a section of the CV.",
          dragHint: "🖱️ MOUSE DRAG:",
          dragDesc: "Rotate orbit.",
          scrollHint: "🖲️ MOUSE SCROLL:",
          scrollDesc: "Zoom control.",
          clickHint: "◎ CLICK PLANET:",
          clickDesc: "Load module.",
          keplerianText: "* Elliptical Keplerian trajectories loaded."
        },
        skills: {
          testResults: "TEST RUNNER RESULTS: 12 PASSED, 0 FAILED",
          systemOnline: "● SYSTEM ONLINE",
          devStack: "💻 TEST SUITE: DEVELOPMENT_STACK",
          qaStack: "🧪 TEST SUITE: QA_AUTOMATION_STACK",
          toolsHeader: "🔧 TOOLS & CI_CD_PIPELINE"
        },
        experience: {
          pipelineHistory: "PIPELINE HISTORY: STABLE",
          status: "STATUS: ACTIVE",
          deploySuccess: "DEPLOY SUCCESS"
        },
        projects: {
          status: "PROJECT INTEGRATION STATUS: ACTIVE",
          repos: "REPOS: {count}",
          telemetrySignal: "TELEMETRY SIGNAL",
          stable: "STABLE",
          viewSource: ">_ VIEW SOURCE"
        },
        education: {
          registrySystem: "CERTIFICATION REGISTRY SYSTEM",
          verified: "VERIFIED: OK",
          academicDegrees: "🎓 ACADEMIC DEGREES",
          certsAndBadges: "🏅 CERTIFICATIONS & BADGES",
          verifiedCheck: "✓ VERIFIED",
          recSystems: "👾 RECREATIONAL SYSTEMS",
          simulationCmd: "$ run simulation --pacman",
          simulationDesc: "Want to try the system's recreational simulation? Control the Sun and eat miniature planets.",
          simulationBtn: "🎮 EXECUTE PACMAN SIMULATION"
        },
        contact: {
          initialized: "COMMUNICATION CHANNEL INITIALIZED",
          txActive: "📡 TX_ACTIVE",
          pingCmd: "> ping -c 1 client-hr",
          pingDesc: "Ready to receive transmissions for job offers, freelance projects, or open-source collaborations. Setup connection below:"
        }
      }
    }
  }
};
